In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier

In [2]:
mvp = pd.read_csv("Data/AllPlayerData.csv")
mvp = mvp.drop("Table Name", axis = 1)
mvp
# mvp_2020 = mvp.loc[mvp["Season"] == "2019-20"]
# mvp_2020

,Player,PlayerID,Pos,Season,Tm,2P,2P%,2PA,3P,3P%,...,GS,MP,ORB,PF,PTS,Rk,STL,TOV,TRB,MVP
0,Mahmoud Abdul-Rauf,abdulma02,PG,2000-01,VAN,116,0.500,232,4,0.286,...,0,486,5,50,266,1,9,26,25,0
1,Tariq Abdul-Wahad,abdulta01,SG,2000-01,DEN,39,0.386,101,4,0.400,...,12,420,14,54,111,2,14,34,59,0
2,Shareef Abdur-Rahim,abdursh01,SF,2000-01,VAN,592,0.487,1216,12,0.188,...,81,3241,175,238,1663,3,90,231,735,0
3,Cory Alexander,alexaco01,PG,2000-01,ORL,14,0.350,40,4,0.250,...,0,227,0,29,52,4,16,25,25,0
4,Courtney Alexander,alexaco02,PG,2000-01,TOT,222,0.421,527,17,0.370,...,24,1382,42,139,618,5,45,75,143,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11713,Thaddeus Young,youngth01,PF,2019-20,CHI,190,0.501,379,79,0.356,...,16,1591,94,134,659,516,92,102,315,0
11714,Trae Young,youngtr01,PG,2019-20,ATL,341,0.501,681,205,0.361,...,60,2120,32,104,1778,517,65,289,255,0
11715,Cody Zeller,zelleco01,C,2019-20,CHO,233,0.577,404,18,0.240,...,39,1341,160,140,642,518,40,75,411,0
11716,Ante Žižić,zizican01,C,2019-20,CLE,41,0.569,72,0,0.000,...,0,221,18,27,96,519,7,10,66,0
11717,Ivica Zubac,zubaciv01,C,2019-20,LAC,203,0.602,337,0,0.000,...,63,1172,167,150,513,520,14,55,464,0

In [3]:
target = mvp["MVP"]
target_names = ["winner", "loser"]

In [4]:
data = mvp.drop(["Player", "PlayerID", "Pos", "Season", "Tm", "Rk", "MVP"], axis=1)
feature_names = data.columns
data.head()

,2P,2P%,2PA,3P,3P%,3PA,Age,AST,BLK,DRB,...,FTA,G,GS,MP,ORB,PF,PTS,STL,TOV,TRB
0,116,0.500,232,4,0.286,14,31,76,1,20,...,29,41,0,486,5,50,266,9,26,25
1,39,0.386,101,4,0.400,10,26,22,13,45,...,36,29,12,420,14,54,111,14,34,59
2,592,0.487,1216,12,0.188,64,24,250,77,560,...,531,81,81,3241,175,238,1663,90,231,735
3,14,0.350,40,4,0.250,16,27,36,0,25,...,18,26,0,227,0,29,52,16,25,25
4,222,0.421,527,17,0.370,46,23,62,5,101,...,150,65,24,1382,42,139,618,45,75,143

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=42)

In [6]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.9969283276450512

In [7]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=200)
rf = rf.fit(X_train, y_train)
test_score = rf.score(X_test, y_test)
train_score = rf.score(X_train, y_train)
print(f"Training Score: {train_score}")
print(f"Test Score: {test_score}")

Training Score: 1.0
Test Score: 0.9976109215017065

In [8]:
importances = rf.feature_importances_
importances

array([0.06976982, 0.02989568, 0.04264486, 0.03094927, 0.03628737,
       0.02263433, 0.0142014 , 0.06717419, 0.01955668, 0.05540627,
       0.03380076, 0.0675827 , 0.03215956, 0.03515262, 0.05055258,
       0.04083894, 0.03116318, 0.02862295, 0.0243224 , 0.02614503,
       0.02167813, 0.06059458, 0.0600961 , 0.0345539 , 0.03285017,
       0.03136653])

In [9]:
sorted(zip(importances, feature_names), reverse=True)

[(0.06976982148845709, '2P'),
 (0.06758269735529851, 'FG'),
 (0.06717419473898191, 'AST'),
 (0.06059457840923002, 'PF'),
 (0.0600960998989577, 'PTS'),
 (0.05540627114239006, 'DRB'),
 (0.050552577057531696, 'FT'),
 (0.042644863259156646, '2PA'),
 (0.04083894100310762, 'FT%'),
 (0.03628736992143913, '3P%'),
 (0.03515261831868043, 'FGA'),
 (0.03455390235550102, 'STL'),
 (0.03380075937584024, 'eFG%'),
 (0.03285017205751372, 'TOV'),
 (0.03215956387051968, 'FG%'),
 (0.03136652517394691, 'TRB'),
 (0.031163175120292257, 'FTA'),
 (0.030949274933088654, '3P'),
 (0.029895676646756117, '2P%'),
 (0.02862294817186287, 'G'),
 (0.026145025932181536, 'MP'),
 (0.024322400856394748, 'GS'),
 (0.022634330628516195, '3PA'),
 (0.021678128195147778, 'ORB'),
 (0.01955668148150985, 'BLK'),
 (0.014201402607697597, 'Age')]