In [23]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import os

In [32]:
mvp = pd.read_csv("Data/MVP.csv")
# mvp = mvp.drop("Unnamed: 0", axis=1)
mvp

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,...,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,season
0,1,Kareem Abdul-Jabbar,32,LAL,147.0,147.0,221,0.665,82,38.3,...,10.8,4.5,1.0,3.4,0.604,0.000,0.765,14.8,0.227,1979-80
1,2,Julius Erving,29,PHI,31.5,31.5,221,0.143,78,36.1,...,7.4,4.6,2.2,1.8,0.519,0.200,0.787,12.5,0.213,1979-80
2,3,George Gervin,27,SAS,19.0,19.0,221,0.086,78,37.6,...,5.2,2.6,1.4,1.0,0.528,0.314,0.852,10.6,0.173,1979-80
3,4,Larry Bird,23,BOS,15.0,15.0,221,0.068,82,36.0,...,10.4,4.5,1.7,0.6,0.474,0.406,0.836,11.2,0.182,1979-80
4,5T,Tiny Archibald,31,BOS,2.0,2.0,221,0.009,80,35.8,...,2.5,8.4,1.3,0.1,0.482,0.222,0.830,8.9,0.148,1979-80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
653,8,Kevin Durant,30,GSW,0.0,25.0,1010,0.025,78,34.6,...,6.4,5.9,0.7,1.1,0.521,0.353,0.885,11.5,0.204,2018-19
654,9,Kawhi Leonard,27,TOR,0.0,13.0,1010,0.013,60,34.0,...,7.3,3.3,1.8,0.4,0.496,0.371,0.854,9.5,0.224,2018-19
655,10,Russell Westbrook,30,OKC,0.0,8.0,1010,0.008,73,36.0,...,11.1,10.7,1.9,0.5,0.428,0.290,0.656,6.8,0.124,2018-19
656,11T,Rudy Gobert,26,UTA,0.0,1.0,1010,0.001,81,31.8,...,12.9,2.0,0.8,2.3,0.669,0.000,0.636,14.4,0.268,2018-19
657,11T,LeBron James,34,LAL,0.0,1.0,1010,0.001,55,35.2,...,8.5,8.3,1.3,0.6,0.510,0.339,0.665,7.2,0.179,2018-19

In [36]:
mvp.dtypes

Rank        object
Player      object
Age          int64
Tm          object
First      float64
Pts Won    float64
Pts Max      int64
Share      float64
G            int64
MP         float64
PTS        float64
TRB        float64
AST        float64
STL        float64
BLK        float64
FG%        float64
3P%        float64
FT%        float64
WS         float64
WS/48      float64
season      object
dtype: object

In [37]:
mvp.astype({"Age": "float64"}).dtypes

Rank        object
Player      object
Age        float64
Tm          object
First      float64
Pts Won    float64
Pts Max      int64
Share      float64
G            int64
MP         float64
PTS        float64
TRB        float64
AST        float64
STL        float64
BLK        float64
FG%        float64
3P%        float64
FT%        float64
WS         float64
WS/48      float64
season      object
dtype: object

In [47]:
mean_mvp = mvp["WS"].mean()
print(f"Average Win Share by MVP candidate: {mean_mvp}")

Average Win Share by MVP candidate: 10.69984802431611

In [38]:
X = mvp.drop(["Rank", "Player", "Tm", "First", "Pts Won", "Pts Max", "Share", "WS", "season"], axis=1)
y = mvp["WS"]
print("Shape: ", X.shape, y.shape)

Shape:  (658, 12) (658,)

In [39]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [40]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

In [41]:
model.fit(X_train, y_train)

LinearRegression()

In [44]:
from sklearn.metrics import mean_squared_error, r2_score

predicted = model.predict(X_test)

# mean squared error and r-squared score
mse = mean_squared_error(y_test, predicted)
r2 = r2_score(y_test, predicted)

print(f"MSE: {mse}")
print(f"R2: {r2}")

MSE: 0.15256068330426462
R2: 0.9841245251632774