In [1]:
import pandas as pd

In [2]:
files = ['rookies_00_01.xlsx',
'rookies_01_02.xlsx',
'rookies_02_03.xlsx',
'rookies_03_04.xlsx',
'rookies_04_05.xlsx',
'rookies_05_06.xlsx',
'rookies_06_07.xlsx',
'rookies_07_08.xlsx',
'rookies_08_09.xlsx',
'rookies_09_10.xlsx',
'rookies_10_11.xlsx',
'rookies_11_12.xlsx',
'rookies_12_13.xlsx',
'rookies_13_14.xlsx',
'rookies_14_15.xlsx',
'rookies_15_16.xlsx',
'rookies_16_17.xlsx',
'rookies_17_18.xlsx',
'rookies_18_19.xlsx',
'rookies_19_20.xlsx',
'rookies_90_91.xlsx',
'rookies_91_92.xlsx',
'rookies_92_93.xlsx',
'rookies_93_94.xlsx',
'rookies_94_95.xlsx',
'rookies_95_96.xlsx',
'rookies_96_97.xlsx',
'rookies_97_98.xlsx',
'rookies_98_99.xlsx',
'rookies_99_00.xlsx']

In [3]:
seasons = ['2000-01','2001-02', '2002-03','2003-04','2004-05','2005-06','2006-07','2007-08','2008-09','2009-10',
          '2010-11','2011-12','2012-13', '2013-14', '2014-15', '2015-16','2016-17', '2017-18','2018-19','2019-20',
          '1990-91','1991-92','1992-93','1993-94','1994-95','1995-96','1996-97','1997-98','1998-99','1999-00']

In [4]:
print(len(files))
print(len(seasons))

30
30

In [5]:
test_zip = zip(files, seasons)
print(*test_zip)

('rookies_00_01.xlsx', '2000-01') ('rookies_01_02.xlsx', '2001-02') ('rookies_02_03.xlsx', '2002-03') ('rookies_03_04.xlsx', '2003-04') ('rookies_04_05.xlsx', '2004-05') ('rookies_05_06.xlsx', '2005-06') ('rookies_06_07.xlsx', '2006-07') ('rookies_07_08.xlsx', '2007-08') ('rookies_08_09.xlsx', '2008-09') ('rookies_09_10.xlsx', '2009-10') ('rookies_10_11.xlsx', '2010-11') ('rookies_11_12.xlsx', '2011-12') ('rookies_12_13.xlsx', '2012-13') ('rookies_13_14.xlsx', '2013-14') ('rookies_14_15.xlsx', '2014-15') ('rookies_15_16.xlsx', '2015-16') ('rookies_16_17.xlsx', '2016-17') ('rookies_17_18.xlsx', '2017-18') ('rookies_18_19.xlsx', '2018-19') ('rookies_19_20.xlsx', '2019-20') ('rookies_90_91.xlsx', '1990-91') ('rookies_91_92.xlsx', '1991-92') ('rookies_92_93.xlsx', '1992-93') ('rookies_93_94.xlsx', '1993-94') ('rookies_94_95.xlsx', '1994-95') ('rookies_95_96.xlsx', '1995-96') ('rookies_96_97.xlsx', '1996-97') ('rookies_97_98.xlsx', '1997-98') ('rookies_98_99.xlsx', '1998-99') ('rookies_99_00.xlsx', '1999-00')

In [7]:
for f, s in zip(files, seasons):
#     print(f)
#     print(s)
#     print('-'*20)
    file_df = pd.read_excel(f)
    file_df.columns = file_df.iloc[0]
    file_df = file_df.drop(file_df.index[0])
    file_df['season'] = s
#     print(file_df)
    file_df.to_excel(f)

In [53]:
# roy = pd.read_excel('rookies_94_95.xlsx')
# roy

In [54]:
roy_files = ['roy_00_01.xlsx',
'roy_01_02.xlsx',
'roy_02_03.xlsx',
'roy_03_04.xlsx',
'roy_04_05.xlsx',
'roy_05_06.xlsx',
'roy_06_07.xlsx',
'roy_07_08.xlsx',
'roy_08_09.xlsx',
'roy_09_10.xlsx',
'roy_10_11.xlsx',
'roy_11_12.xlsx',
'roy_12_13.xlsx',
'roy_13_14.xlsx',
'roy_14_15.xlsx',
'roy_15_16.xlsx',
'roy_16_17.xlsx',
'roy_17_18.xlsx',
'roy_18_19.xlsx',
'roy_90_91.xlsx',
'roy_91_92.xlsx',
'roy_92_93.xlsx',
'roy_93_94.xlsx',
'roy_94_95.xlsx',
'roy_95_96.xlsx',
'roy_96_97.xlsx',
'roy_97_98.xlsx',
'roy_98_99.xlsx',
'roy_99_00.xlsx']

In [55]:
seasons_2 = ['2000-01','2001-02', '2002-03','2003-04','2004-05','2005-06','2006-07','2007-08','2008-09','2009-10',
          '2010-11','2011-12','2012-13', '2013-14', '2014-15', '2015-16','2016-17', '2017-18','2018-19',
          '1990-91','1991-92','1992-93','1993-94','1994-95','1995-96','1996-97','1997-98','1998-99','1999-00']

In [56]:
print(len(roy_files))
print(len(seasons_2))

29
29

In [57]:
roy_zip = zip(roy_files, seasons_2)
print(*roy_zip)

('roy_00_01.xlsx', '2000-01') ('roy_01_02.xlsx', '2001-02') ('roy_02_03.xlsx', '2002-03') ('roy_03_04.xlsx', '2003-04') ('roy_04_05.xlsx', '2004-05') ('roy_05_06.xlsx', '2005-06') ('roy_06_07.xlsx', '2006-07') ('roy_07_08.xlsx', '2007-08') ('roy_08_09.xlsx', '2008-09') ('roy_09_10.xlsx', '2009-10') ('roy_10_11.xlsx', '2010-11') ('roy_11_12.xlsx', '2011-12') ('roy_12_13.xlsx', '2012-13') ('roy_13_14.xlsx', '2013-14') ('roy_14_15.xlsx', '2014-15') ('roy_15_16.xlsx', '2015-16') ('roy_16_17.xlsx', '2016-17') ('roy_17_18.xlsx', '2017-18') ('roy_18_19.xlsx', '2018-19') ('roy_90_91.xlsx', '1990-91') ('roy_91_92.xlsx', '1991-92') ('roy_92_93.xlsx', '1992-93') ('roy_93_94.xlsx', '1993-94') ('roy_94_95.xlsx', '1994-95') ('roy_95_96.xlsx', '1995-96') ('roy_96_97.xlsx', '1996-97') ('roy_97_98.xlsx', '1997-98') ('roy_98_99.xlsx', '1998-99') ('roy_99_00.xlsx', '1999-00')

In [58]:
for f, s in zip(roy_files, seasons_2):
    print(f)
    print(s)
    print('-'*20)
    file_df = pd.read_excel(f)
    file_df.columns = file_df.iloc[0]
    file_df = file_df.drop(file_df.index[0])
    file_df['season'] = s
#     print(file_df)
    file_df.to_excel(f)

roy_00_01.xlsx
2000-01
--------------------
roy_01_02.xlsx
2001-02
--------------------
roy_02_03.xlsx
2002-03
--------------------
roy_03_04.xlsx
2003-04
--------------------
roy_04_05.xlsx
2004-05
--------------------
roy_05_06.xlsx
2005-06
--------------------
roy_06_07.xlsx
2006-07
--------------------
roy_07_08.xlsx
2007-08
--------------------
roy_08_09.xlsx
2008-09
--------------------
roy_09_10.xlsx
2009-10
--------------------
roy_10_11.xlsx
2010-11
--------------------
roy_11_12.xlsx
2011-12
--------------------
roy_12_13.xlsx
2012-13
--------------------
roy_13_14.xlsx
2013-14
--------------------
roy_14_15.xlsx
2014-15
--------------------
roy_15_16.xlsx
2015-16
--------------------
roy_16_17.xlsx
2016-17
--------------------
roy_17_18.xlsx
2017-18
--------------------
roy_18_19.xlsx
2018-19
--------------------
roy_90_91.xlsx
1990-91
--------------------
roy_91_92.xlsx
1991-92
--------------------
roy_92_93.xlsx
1992-93
--------------------
roy_93_94.xlsx
1993-94
--------------------
roy_94_95.xlsx
1994-95
--------------------
roy_95_96.xlsx
1995-96
--------------------
roy_96_97.xlsx
1996-97
--------------------
roy_97_98.xlsx
1997-98
--------------------
roy_98_99.xlsx
1998-99
--------------------
roy_99_00.xlsx
1999-00
--------------------

In [60]:
# pd.read_excel('roy_92_93.xlsx')

In [38]:
print(len(files))

30

In [19]:
all_rookies_df = pd.DataFrame()

In [20]:
for file in files:
    a = pd.read_excel(file)
    b = pd.DataFrame(a)
#     print(b.columns)
    all_rookies_df = all_rookies_df.append(b)
#     print(b)

In [21]:
all_rookies_df

,Unnamed: 0,Rk,Player,Debut,Age,Yrs,G,MP,FG,FGA,...,PF,PTS,FG%,3P%,FT%,MP.1,PTS.1,TRB.1,AST.1,season
0,1,1,Courtney Alexander,"Nov 4, '00, DAL vs. UTA",23,1,65,1382,239,573,...,139,618,0.417,0.370,0.820,21.3,9.5,2.2,1.0,2000-01
1,2,2,Dalibor Bagarić,"Nov 22, '00, CHI @ SAC",20,1,35,259,17,65,...,44,47,0.262,0.000,0.464,7.4,1.3,1.6,0.3,2000-01
2,3,3,Erick Barkley,"Nov 2, '00, POR @ PHO",22,1,8,38,8,22,...,2,19,0.364,0.375,NaN,4.8,2.4,0.4,0.8,2000-01
3,4,4,Raja Bell,"Apr 6, '01, PHI vs. CLE",24,1,5,30,2,7,...,1,5,0.286,0.333,NaN,6.0,1.0,0.2,0.0,2000-01
4,5,5,Mark Blount,"Nov 1, '00, BOS vs. DET",25,1,64,1098,101,200,...,183,248,0.505,NaN,0.697,17.2,3.9,3.6,0.5,2000-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55,56,56,Mirsad Türkcan,"Nov 19, '99, NYK @ PHO",23,1,17,90,14,38,...,14,33,0.368,0.000,0.625,5.3,1.9,1.9,0.3,1999-00
56,57,57,Wayne Turner,"Nov 2, '99, BOS @ TOR",23,1,3,41,1,6,...,4,4,0.167,NaN,0.333,13.7,1.3,1.0,1.7,1999-00
57,58,58,Dedric Willoughby,"Nov 5, '99, CHI vs. MIA",25,1,25,508,61,179,...,32,190,0.341,0.296,0.765,20.3,7.6,2.0,2.6,1999-00
58,59,59,Metta World Peace,"Nov 3, '99, CHI vs. NYK",20,1,72,2238,309,759,...,159,866,0.407,0.314,0.674,31.1,12.0,4.3,2.8,1999-00
59,60,60,Tim Young,"Nov 16, '99, GSW vs. CHI",23,1,25,137,13,39,...,18,54,0.333,NaN,0.778,5.5,2.2,1.4,0.2,1999-00

In [22]:
all_rookies_df.to_excel("all_rookies_1990_2020.xlsx")
# df1.to_excel("output.xlsx")

In [27]:
print(all_rookies_df['season'].unique())

['2000-01' '2001-02' '2002-03' '2003-04' '2004-05' '2005-06' '2006-07'
 '2007-08' '2008-09' '2009-10' '2010-11' '2011-12' '2012-13' '2013-14'
 '2014-15' '2015-16' '2016-17' '2017-18' '2018-19' '2019-20' '1990-91'
 '1991-92' '1992-93' '1993-94' '1994-95' '1995-96' '1996-97' '1997-98'
 '1998-99' '1999-00']

In [61]:
all_roy_df = pd.DataFrame()

In [62]:
for file in roy_files:
    a = pd.read_excel(file)
    b = pd.DataFrame(a)
#     print(b.columns)
    all_roy_df = all_roy_df.append(b)

In [63]:
all_roy_df['season'].unique()

array(['2000-01', '2001-02', '2002-03', '2003-04', '2004-05', '2005-06',
       '2006-07', '2007-08', '2008-09', '2009-10', '2010-11', '2011-12',
       '2012-13', '2013-14', '2014-15', '2015-16', '2016-17', '2017-18',
       '2018-19', '1990-91', '1991-92', '1992-93', '1993-94', '1994-95',
       '1995-96', '1996-97', '1997-98', '1998-99', '1999-00'],
      dtype=object)

In [64]:
all_roy_df.to_excel("all_roy_candidates_1990_2020.xlsx")